name: "BedwarsRel"
description: |
  §aBedwars Reloaded - The Minecraft Bedwars Plugin!
  §7Bedwars is a Minecraft minigame where teams (max. 15) try to destroy the other teams' beds. But there is more: On the whole map there are ressource spawners spawning items. Some items are more worth than others and with these you can buy different things in the so called "Villager Shop". You will find powerful weapons or potions or simple blocks to get to the other bases. Get to the others bases? Yes, every team starts on an island and you have to get to the others with blocks which you can buy in the "Villager Shop". When you meet a enemy you have to try to kill him so he'll lose all the equipment which he had in his inventory. As soon as a team's bed is destroyed they cannot respawn again and last team standing wins.
author: "The BedwarsRel-Team | www.github.com/orgs/BedwarsRel/people"
website: "www.github.com/BedwarsRel"

main: at.kaindorf.games.BedwarsRel
version: ${versionstring}

awareness:
  - !@UTF8

depend: [ ]
softdepend: [ Multiverse-Core, Multiworld, MultiWorld, HolographicDisplays, HologramAPI, UltimateCore ]

commands:
  bw:
    description: Base command for all Test-Plugin commands
    usage: /<command> help
    permission: bw.base
  # commands for tournaments
  tourney:
    description: Base command for all Tournament commands
    usage: /<command> help
    permission: tourney.manage

permissions:
  bw.base:
    description: Allows you to show to play games
    default: true
  bw.setup:
    description: Allows you to set up new or existing games
    default: op
  bw.kick:
    description: Allows a player to kick other players from the game
    default: op
  bw.vip.*:
    description: Allows special user permissions
    default: op
    children:
      bw.vip.joinfull: true
      bw.vip.forcestart: true
      bw.vip.reducecountdown: true
      bw.vip.skipbalance: true
  bw.cmd:
    description: Allows to execute non-bedwars commands ingame
    default: op
  bw.otherstats:
    description: Allows to show stats of other players
    default: op
  # permissions for tournaments
  tourney.manage:
    description: Allows to manage a tournament
    default: op
  tourney.player:
    description: Allows players to use show commands
    default: true
